add

diff --git a/.github/workflows/ios_build_noscript.yml b/.github/workflows/ios_build_noscript.yml
--- a/.github/workflows/ios_build_noscript.yml
+++ b/.github/workflows/ios_build_noscript.yml
@@ -110,6 +110,8 @@ jobs:
         if: failure()
         run: |
           ls /Users/runner/Library/Logs/gym/ || true
+            
           FLAVOR="${{ matrix.flavor }}"
-          cat /Users/runner/Library/Logs/gym/Runner-${FLAVOR}.log  || true
-       
+          filename = "/Users/runner/Library/Logs/gym/Runner-${FLAVOR}.log"
+          echo "=== Printing Runner-${FLAVOR}.log === FLAVOR=${FLAVOR} ${filename}"
+          cat filename || echo "Log file not found"       
